# Generated by Django 3.2.5 on 2021-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
