# Generated by Django 3.2.6 on 2021-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_alter_bar_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
