# Generated by Django 3.2.6 on 2021-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_alter_barimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimage',
            name='description',
        ),
    ]
