# Generated by Django 3.2.6 on 2021-10-30 16:25

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_alter_bar_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='image_file',
            field=models.ImageField(default=False, upload_to=apps.bars.models.upload_to),
        ),
    ]
