# Generated by Django 3.2.6 on 2021-11-27 10:54

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_remove_barimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to_bar_images_folder),
        ),
    ]
