# Generated by Django 3.2.6 on 2021-10-31 00:03

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_bar_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='image_file',
            field=models.ImageField(upload_to=apps.bars.models.upload_to),
        ),
    ]
