# Generated by Django 3.2.6 on 2021-10-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_alter_bar_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='image_file',
            new_name='imagefile',
        ),
    ]
