# Generated by Django 3.2.6 on 2021-10-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0006_rename_image_file_bar_imagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='imagefile',
            new_name='image_file',
        ),
    ]
