# Generated by Django 3.2.6 on 2021-10-31 01:29

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0007_rename_imagefile_bar_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=32)),
                ('image_file', models.ImageField(upload_to=apps.bars.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='bar',
            name='image_file',
        ),
    ]
