# Generated by Django 3.2.6 on 2021-10-31 01:39

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0008_auto_20211031_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='image_file',
            field=models.ImageField(upload_to=apps.bars.models.upload_to),
        ),
    ]
