# Generated by Django 3.2.6 on 2021-10-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0010_alter_bar_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='image_file',
        ),
    ]
