# Generated by Django 3.2.6 on 2021-11-01 23:03

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0011_remove_bar_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='image_file',
            field=models.ImageField(default='/Users/jacobo/Documents/glub-api/mediabaricons/default_image.png', upload_to=apps.bars.models.upload_to),
        ),
    ]
