# Generated by Django 3.2.6 on 2021-11-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0011_bar_current_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='image_file',
            new_name='logo',
        ),
    ]
