# Generated by Django 3.2.6 on 2021-11-03 08:29

import apps.bars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0012_rename_image_file_bar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to),
        ),
    ]
