# Generated by Django 3.2.6 on 2021-11-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0013_alter_bar_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarIcon',
        ),
    ]
