# Generated by Django 3.2.6 on 2021-11-17 19:14

import apps.bars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0014_delete_baricon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to_bar_images_folder)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to_bar_images_folder)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to_bar_images_folder)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to_bar_images_folder)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=apps.bars.models.upload_to_bar_images_folder)),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
            ],
        ),
    ]
