# Generated by Django 3.2.6 on 2021-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0015_barimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barimages',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='barimages',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='barimages',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='barimages',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='barimages',
            name='image5',
        ),
        migrations.AddField(
            model_name='barimages',
            name='description',
            field=models.IntegerField(default=100),
        ),
    ]
