# Generated by Django 3.2.5 on 2021-08-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('license_number', models.CharField(max_length=255)),
            ],
            bases=('accounts.userprofile',),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
            bases=('accounts.userprofile',),
        ),
    ]
