# Generated by Django 3.2.6 on 2021-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210801_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=659699669, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_number',
            field=models.CharField(default='45845856W', max_length=9),
            preserve_default=False,
        ),
    ]
