# Generated by Django 3.2.6 on 2021-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210929_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=23, max_length=9),
            preserve_default=False,
        ),
    ]
