version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=glub
      - POSTGRES_USER=glub
      - POSTGRES_PASSWORD=glub-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432