version: '3'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=glub
      - POSTGRES_USER=glub
      - POSTGRES_PASSWORD=glub-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432