# Generated by Django 3.1.6 on 2021-02-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerinfo',
            old_name='NIF',
            new_name='nif',
        ),
    ]
