# Generated by Django 3.2.6 on 2021-09-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_alter_bar_owner'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='date_scanned',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='slug',
        ),
        migrations.AddField(
            model_name='registry',
            name='bar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bars.bar'),
            preserve_default=False,
        ),
    ]
